version: '3.1'

services:

  db:
    # will build .docker/db/Dockerfile
    image: postgres:10-alpine
    #build: ./docker/db
    restart: always
    #environment:
    #  POSTGRES_DB: db
    #  POSTGRES_USER: docker
    #  POSTGRES_PASSWORD: dockerPassword
    ports:
      - "5432:5432"
    volumes:
      - db_start_django:/var/lib/postgresql/data

  web:
    build: ./docker/web
    restart: always
    environment:
      CLOUDINARY_URL: cloudinary://315421421813724:MzHbUUMPd0iKzZcCD3QDwub5tYk@pawlissimo
      CLOUDINARY_CLOUD_NAME: "pawlissimo"
      CLOUDINARY_API_KEY: "315421421813724"
      CLOUDINARY_API_SECRET: "MzHbUUMPd0iKzZcCD3QDwub5tYk"
    volumes:
      - ./project:/code
      - docker_build:/build
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: python3 manage.py runserver 0.0.0.0:8000

volumes:
  db_start_django:
  docker_build:
