version: '3.1'

services:

  db:
    # will build .docker/db/Dockerfile
    image: postgres:10-alpine
    #build: ./docker/db
    restart: always
    #environment:
    #  POSTGRES_DB: db
    #  POSTGRES_USER: docker
    #  POSTGRES_PASSWORD: dockerPassword
    ports:
      - "5432:5432"
    volumes:
      - db-test_django:/var/lib/postgresql/data

  web:
    build: ./docker/web
    restart: always
    volumes:
      - .:/code
    ports:
      - "8008:8000"
    depends_on:
      - db
    command: python3 manage.py runserver 0.0.0.0:8000

